[config]
schemaVersion = "0.0.1"

[package]
namespace = "MoSadie"
name = "SlipStreamerBot"
versionNumber = "1.2.3"
description = "Trigger Streamer.bot Actions based on in-game events!"
websiteUrl = "https://github.com/MoSadie/SlipStreamer.bot"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack= "5.4.2100"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./SlipStreamer.bot/bin/Release/netstandard2.1/com.mosadie.slipstreamerbot.dll"
target = "BepInEx/plugins/MoSadie-SlipStreamerBot/com.mosadie.slipstreamerbot.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./ImportSlipStreamerBot.txt"
target = "./ImportSlipStreamerBot.txt"

[publish]
repository = "https://thunderstore.io"
communities = [ "slipstream-rogue-space", ]
[publish.categories]
slipstream-rogue-space = [ "mods" ]


