[config]
schemaVersion = "0.0.1"

[package]
namespace = "MoSadie"
name = "SlipEvent"
versionNumber = "2.0.0"
description = "Send in-game events to external software"
websiteUrl = "https://github.com/MoSadie/SlipEvent"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack= "5.4.2100"
MoSadie-MoCore= "1.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./SlipEvent/bin/Release/netstandard2.1/com.mosadie.slipevent.dll"
target = "BepInEx/plugins/MoSadie-SlipEvent/com.mosadie.slipevent.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./ImportSlipStreamerBot.txt"
target = "./ImportSlipStreamerBot.txt"

[publish]
repository = "https://thunderstore.io"
communities = [ "slipstream-rogue-space", ]
[publish.categories]
slipstream-rogue-space = [ "mods" ]


